# Generated by Django 5.2.4 on 2025-08-07 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rsvp_event_rsvp_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsvp',
            name='status',
        ),
    ]
