# Generated by Django 5.2.4 on 2025-08-07 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_userprofile_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='events/defaults/default_event.svg', null=True, upload_to='events/'),
        ),
    ]
